export const styles = {
  container: { fontFamily: '"Poppins", sans-serif', margin: 0, backgroundColor: '#fff', overflowX: 'hidden' },
  
  heroSection: { position: 'relative', color: 'white', padding: '100px 20px', overflow: 'hidden' },
  heroOverlay: { position: 'absolute', inset: 0, opacity: 0.85, zIndex: 1 },
  heroContent: { position: 'relative', zIndex: 2, maxWidth: '1200px', margin: '0 auto', textAlign: 'left' },
  heading: { fontWeight: '800', fontSize: '48px', margin: '0' },
  underline: { width: '80px', height: '5px', margin: '15px 0 25px' },
  description: { fontSize: '19px', lineHeight: '1.7', color: '#fff', maxWidth: '850px', fontWeight: '500' },
  
  statsSection: { padding: '80px 20px', position: 'relative', zIndex: 3 },
  statsGrid: { maxWidth: '1200px', margin: '0 auto', display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))', gap: '30px' },
  statCard: { display: 'flex', flexDirection: 'column', alignItems: 'center', textAlign: 'center' },
  iconWrapper: { backgroundColor: '#fff', padding: '25px', borderRadius: '20px', marginBottom: '15px', border: '1px solid #fdf2f8', display: 'flex', alignItems: 'center', justifyContent: 'center' },
  statValue: { fontSize: '32px', fontWeight: '800', margin: '0' },
  statLabel: { fontSize: '14px', color: '#64748b', fontWeight: '600' },

  storySection: { padding: '100px 20px' },
  storyContainer: { maxWidth: '1200px', margin: '0 auto', display: 'flex', gap: '60px', alignItems: 'center' },
  founderCardWrapper: { flex: '0 0 350px' },
  founderCard: { borderRadius: '24px', overflow: 'hidden', boxShadow: '0 20px 40px rgba(0,0,0,0.08)', backgroundColor: '#fff' },
  imageArea: { height: '420px', overflow: 'hidden' },
  founderImg: { width: '100%', height: '100%', objectFit: 'cover', display: 'block' },
  founderInfo: { padding: '25px', textAlign: 'center' },
  founderName: { margin: '0', fontSize: '22px', fontWeight: '800' },
  founderTitle: { margin: '5px 0 0', fontSize: '13px', color: '#64748b', fontWeight: '600' },
  storyTextContent: { flex: '1' },
  storyHeading: { fontWeight: '900', lineHeight: '1.2' },
  storyUnderline: { width: '100px', height: '4px', marginBottom: '30px' },
  storyParagraph: { fontSize: '16.5px', lineHeight: '1.9', color: '#334155', marginBottom: '20px' },
  signature: { fontWeight: '800', fontSize: '18px' },

  valuesSection: { padding: '100px 20px', backgroundColor: '#fff' },
  valuesHeader: { textAlign: 'center', marginBottom: '50px' },
  valuesHeading: { fontWeight: '900', fontSize: '36px' },
  valuesUnderline: { width: '80px', height: '5px', margin: '15px auto 30px' },
  valuesSubtext: { fontSize: '18px', color: '#64748b', fontWeight: '500' },
  valuesGrid: { maxWidth: '1200px', margin: '0 auto', display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))', gap: '25px' },
  valueCard: { backgroundColor: '#fff', padding: '40px', borderRadius: '24px' },
  valueIcon: { marginBottom: '20px', display: 'inline-block' },
  valueTitle: { fontSize: '22px', fontWeight: '800', marginBottom: '15px' },
  valueText: { fontSize: '15px', lineHeight: '1.7', color: '#475569' },

  legalSection: { padding: '120px 20px' },
  legalContainer: { maxWidth: '1200px', margin: '0 auto', display: 'flex', alignItems: 'center', gap: '80px' },
  infoCard: { flex: '1', backgroundColor: '#fff', padding: '50px', borderRadius: '30px', boxShadow: '0 30px 60px rgba(0,0,0,0.05)', position: 'relative' },
  cardAccent: { position: 'absolute', top: '50px', left: '0', width: '6px', height: '40px', borderRadius: '0 10px 10px 0' },
  legalHeading: { fontWeight: '900', fontSize: '32px' },
  legalSubtext: { fontSize: '16px', color: '#64748b', marginBottom: '45px', fontWeight: '500' },
  detailsGrid: { display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '30px', marginBottom: '40px' },
  detailItem: { display: 'flex', gap: '15px', alignItems: 'flex-start' },
  detailLabel: { display: 'block', fontSize: '12px', fontWeight: '800', color: '#94a3b8', textTransform: 'uppercase', letterSpacing: '0.5px' },
  detailValue: { fontSize: '15px', fontWeight: '700', marginTop: '3px' },
  policyBadgeContainer: { display: 'flex', gap: '12px', flexWrap: 'wrap', marginBottom: '40px' },
  policyBadge: { backgroundColor: '#fdf2f8', border: 'none', padding: '10px 20px', borderRadius: '100px', fontSize: '13px', fontWeight: '700', cursor: 'pointer' },
  mainBtn: { color: '#fff', border: 'none', padding: '18px', borderRadius: '15px', fontSize: '16px', fontWeight: '800', width: '100%', cursor: 'pointer' },
  imageGallery: { flex: '1', position: 'relative', height: '450px' },
  galleryImg: { borderRadius: '25px', overflow: 'hidden', border: '8px solid #fff', boxShadow: '0 25px 50px rgba(0,0,0,0.08)' },
  imgLarge: { width: '85%', height: '380px', position: 'absolute', top: '0', right: '0' },
  imgSmall: { width: '50%', height: '260px', position: 'absolute', bottom: '0', left: '0', zIndex: '2' },
  imgPlaceholder: { width: '100%', height: '100%' }
};