export const styles = {
  pageWrapper: { minHeight: '100vh', overflowX: 'hidden' },
  heroBanner: { width: '100%', height: '400px', display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '0 10%', position: 'relative', color: '#fff', marginBottom: '20px' },
  heroOverlayContent: { zIndex: 2, flex: 1 },
  heroHeading: { fontSize: 'clamp(40px, 6vw, 64px)', fontWeight: '900', margin: 0, lineHeight: '1.1', letterSpacing: '-2px' },
  heroSubHeading: { fontSize: '20px', fontWeight: '500', marginTop: '18px', maxWidth: '500px', opacity: 0.95 },
  heroImageContainer: { height: '100%', display: 'flex', alignItems: 'flex-end', justifyContent: 'flex-end', flex: 1 },
  heroImg: { height: '90%', objectFit: 'contain', filter: 'drop-shadow(0 20px 40px rgba(0,0,0,0.2))' },
  headerArea: { textAlign: 'center', padding: '50px 20px 30px', backgroundColor: '#fff', borderBottom: '1px solid rgba(0,0,0,0.05)' },
  mainTitle: { fontSize: '38px', fontWeight: '900', marginBottom: '25px', letterSpacing: '-1px' },
  searchContainer: { position: 'relative', maxWidth: '600px', margin: '0 auto 35px', boxShadow: '0 15px 35px rgba(142, 35, 130, 0.1)', borderRadius: '50px' },
  searchInput: { width: '100%', padding: '20px 35px', borderRadius: '50px', border: '1.5px solid transparent', outline: 'none', fontSize: '16px', backgroundColor: '#fdfcfd' },
  searchIcon: { position: 'absolute', right: '25px', top: '22px' },
  categoryNav: { display: 'flex', gap: '15px', overflowX: 'auto', padding: '10px 0 20px', maxWidth: '1200px', margin: '0 auto', cursor: 'grab' },
  categoryPill: { padding: '14px 32px', borderRadius: '50px', whiteSpace: 'nowrap', fontSize: '14px', fontWeight: '800', cursor: 'pointer', border: '2.5px solid', transition: 'background-color 0.3s ease, color 0.3s ease' },
  feedContainer: { maxWidth: '1400px', margin: '40px auto', padding: '0 20px 100px' },
  cardGrid: { display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(280px, 1fr))', gap: '30px' },
  causeCard: { borderRadius: '24px', overflow: 'hidden', height: '380px', position: 'relative', backgroundColor: '#fff' },
  cardImageWrapper: { height: '100%', width: '100%', position: 'relative', overflow: 'hidden' },
  cardImgTag: { width: '100%', height: '100%', objectFit: 'cover', display: 'block' },
  cardOverlay: { position: 'absolute', bottom: 0, left: 0, right: 0, padding: '25px', background: 'linear-gradient(transparent, rgba(142, 35, 130, 0.95))', color: '#fff', zIndex: 3 },
  cardCatTag: { fontSize: '10px', padding: '4px 12px', borderRadius: '50px', fontWeight: '900', textTransform: 'uppercase', letterSpacing: '1px' },
  cardCaption: { marginTop: '12px', fontSize: '15px', fontWeight: '700', lineHeight: '1.3' },
  whatsappBadge: { position: 'absolute', top: '20px', right: '20px', backgroundColor: '#25D366', width: '40px', height: '40px', borderRadius: '50%', display: 'flex', alignItems: 'center', justifyContent: 'center', cursor: 'pointer', zIndex: 5, boxShadow: '0 8px 16px rgba(0,0,0,0.2)' },
  fab: { position: 'fixed', bottom: '50px', right: '50px', width: '75px', height: '75px', borderRadius: '50%', color: '#fff', border: 'none', boxShadow: '0 15px 35px rgba(142, 35, 130, 0.3)', cursor: 'pointer', zIndex: 100, display: 'flex', alignItems: 'center', justifyContent: 'center' },
  modalOverlay: { position: 'fixed', inset: 0, background: 'rgba(26, 10, 24, 0.8)', display: 'flex', justifyContent: 'center', alignItems: 'center', zIndex: 1000, backdropFilter: 'blur(10px)' },
  modalContent: { background: '#fff', padding: '40px', borderRadius: '35px', width: '90%', maxWidth: '500px' },
  uploadBox: { height: '260px', border: '2.5px dashed', borderRadius: '24px', display: 'flex', justifyContent: 'center', alignItems: 'center', cursor: 'pointer', overflow: 'hidden', position: 'relative' },
  preview: { width: '100%', height: '100%', objectFit: 'cover' },
  submitBtn: { width: '100%', padding: '20px', color: '#fff', border: 'none', borderRadius: '50px', marginTop: '30px', fontWeight: '900', fontSize: '16px', letterSpacing: '1px', cursor: 'pointer' },
  cardSkeleton: { height: '380px', width: '100%' }
};